__author__ = "Ilia Sagaidak"
__copyright__ = "Copyright 2022, ISG Neuro"
__credits__ = []
__license__ = ""
__version__ = "0.2.2"
__api_version__ = "1"
__maintainer__ = "Ilia Sagaidak"
__email__ = "isagaidak@isgneuro.com"
__status__ = "Dev"
