# Generated by Django 3.2.9 on 2022-09-08 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import rest_auth.models.abc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacesKeychain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('_zone', models.IntegerField(blank=True, null=True)),
                ('_permits', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
            ],
            options={
                'abstract': False,
            },
            bases=(rest_auth.models.abc.IKeyChain, models.Model),
        ),
        migrations.CreateModel(
            name='ProtectedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=256, unique=True)),
                ('owner', models.IntegerField()),
                ('keychain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_resources', to='dtcd_workspaces.workspaceskeychain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
